// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: frameStreamService.proto

package streamgRPCspec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request mand response frame structure.
type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client string `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Qos    string `protobuf:"bytes,3,opt,name=qos,proto3" json:"qos,omitempty"`
	Data   []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // generic data byte array containing the expected input and output data of the AR Service
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frameStreamService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_frameStreamService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_frameStreamService_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *Frame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Frame) GetQos() string {
	if x != nil {
		return x.Qos
	}
	return ""
}

func (x *Frame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_frameStreamService_proto protoreflect.FileDescriptor

var file_frameStreamService_proto_rawDesc = []byte{
	0x0a, 0x18, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x05, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x71,
	0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x71, 0x6f, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x39, 0x0a, 0x13, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x06, 0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x1a, 0x06, 0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x12, 0x5a, 0x10,
	0x2e, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x67, 0x52, 0x50, 0x43, 0x73, 0x70, 0x65, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_frameStreamService_proto_rawDescOnce sync.Once
	file_frameStreamService_proto_rawDescData = file_frameStreamService_proto_rawDesc
)

func file_frameStreamService_proto_rawDescGZIP() []byte {
	file_frameStreamService_proto_rawDescOnce.Do(func() {
		file_frameStreamService_proto_rawDescData = protoimpl.X.CompressGZIP(file_frameStreamService_proto_rawDescData)
	})
	return file_frameStreamService_proto_rawDescData
}

var file_frameStreamService_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_frameStreamService_proto_goTypes = []interface{}{
	(*Frame)(nil), // 0: Frame
}
var file_frameStreamService_proto_depIdxs = []int32{
	0, // 0: FramesStreamService.StreamFrames:input_type -> Frame
	0, // 1: FramesStreamService.StreamFrames:output_type -> Frame
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_frameStreamService_proto_init() }
func file_frameStreamService_proto_init() {
	if File_frameStreamService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_frameStreamService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frameStreamService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frameStreamService_proto_goTypes,
		DependencyIndexes: file_frameStreamService_proto_depIdxs,
		MessageInfos:      file_frameStreamService_proto_msgTypes,
	}.Build()
	File_frameStreamService_proto = out.File
	file_frameStreamService_proto_rawDesc = nil
	file_frameStreamService_proto_goTypes = nil
	file_frameStreamService_proto_depIdxs = nil
}
