// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: frameStreamService.proto

package streamgRPCspec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Threshold type
type StreamFrameThreshold struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Current   float32 `protobuf:"fixed32,2,opt,name=current,proto3" json:"current,omitempty"`
	Threshold float32 `protobuf:"fixed32,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
}

func (x *StreamFrameThreshold) Reset() {
	*x = StreamFrameThreshold{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frameStreamService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamFrameThreshold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFrameThreshold) ProtoMessage() {}

func (x *StreamFrameThreshold) ProtoReflect() protoreflect.Message {
	mi := &file_frameStreamService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFrameThreshold.ProtoReflect.Descriptor instead.
func (*StreamFrameThreshold) Descriptor() ([]byte, []int) {
	return file_frameStreamService_proto_rawDescGZIP(), []int{0}
}

func (x *StreamFrameThreshold) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StreamFrameThreshold) GetCurrent() float32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *StreamFrameThreshold) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

// The request and response frame structure.
type StreamFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client    string                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Id        string                `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Qos       string                `protobuf:"bytes,3,opt,name=qos,proto3" json:"qos,omitempty"`
	Threshold *StreamFrameThreshold `protobuf:"bytes,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Data      []byte                `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"` // generic data byte array containing the expected input and output data of the AR Service
}

func (x *StreamFrame) Reset() {
	*x = StreamFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frameStreamService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFrame) ProtoMessage() {}

func (x *StreamFrame) ProtoReflect() protoreflect.Message {
	mi := &file_frameStreamService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFrame.ProtoReflect.Descriptor instead.
func (*StreamFrame) Descriptor() ([]byte, []int) {
	return file_frameStreamService_proto_rawDescGZIP(), []int{1}
}

func (x *StreamFrame) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *StreamFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamFrame) GetQos() string {
	if x != nil {
		return x.Qos
	}
	return ""
}

func (x *StreamFrame) GetThreshold() *StreamFrameThreshold {
	if x != nil {
		return x.Threshold
	}
	return nil
}

func (x *StreamFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_frameStreamService_proto protoreflect.FileDescriptor

var file_frameStreamService_proto_rawDesc = []byte{
	0x0a, 0x18, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x14, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f,
	0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x22, 0x90,
	0x01, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x6f, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x71, 0x6f, 0x73, 0x12, 0x33, 0x0a, 0x09, 0x74, 0x68, 0x72, 0x65,
	0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f,
	0x6c, 0x64, 0x52, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x45, 0x0a, 0x13, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x0c, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x1a, 0x0c, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x67, 0x52, 0x50, 0x43, 0x73, 0x70, 0x65, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_frameStreamService_proto_rawDescOnce sync.Once
	file_frameStreamService_proto_rawDescData = file_frameStreamService_proto_rawDesc
)

func file_frameStreamService_proto_rawDescGZIP() []byte {
	file_frameStreamService_proto_rawDescOnce.Do(func() {
		file_frameStreamService_proto_rawDescData = protoimpl.X.CompressGZIP(file_frameStreamService_proto_rawDescData)
	})
	return file_frameStreamService_proto_rawDescData
}

var file_frameStreamService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_frameStreamService_proto_goTypes = []interface{}{
	(*StreamFrameThreshold)(nil), // 0: StreamFrameThreshold
	(*StreamFrame)(nil),          // 1: StreamFrame
}
var file_frameStreamService_proto_depIdxs = []int32{
	0, // 0: StreamFrame.threshold:type_name -> StreamFrameThreshold
	1, // 1: FramesStreamService.StreamFrames:input_type -> StreamFrame
	1, // 2: FramesStreamService.StreamFrames:output_type -> StreamFrame
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_frameStreamService_proto_init() }
func file_frameStreamService_proto_init() {
	if File_frameStreamService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_frameStreamService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamFrameThreshold); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frameStreamService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frameStreamService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frameStreamService_proto_goTypes,
		DependencyIndexes: file_frameStreamService_proto_depIdxs,
		MessageInfos:      file_frameStreamService_proto_msgTypes,
	}.Build()
	File_frameStreamService_proto = out.File
	file_frameStreamService_proto_rawDesc = nil
	file_frameStreamService_proto_goTypes = nil
	file_frameStreamService_proto_depIdxs = nil
}
